### ISSUE TITLE
form submission issues

### ISSUE THREAD

**Issue by duquej** [duquej/matchmocker#12]
* investigate issues with undefined zoomlink value in form

* (Rare error i havent seen before) Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.
[0]     at Object.validateResourcePath (C:\Users\owner\Desktop\repo\matchmocker\functions\node_modules\@google-cloud\firestore\build\src\path.js:407:15)
[0]     at CollectionReference.doc (C:\Users\owner\Desktop\repo\matchmocker\functions\node_modules\@google-cloud\firestore\build\src\reference.js:1942:20)
[0]     at Object.handleNewInterviewRequest (C:\Users\owner\Desktop\repo\matchmocker\db-functions.js:231:55)
[0]     at C:\Users\owner\Desktop\repo\matchmocker\server.js:143:6

**Comment by duquej** [comment]
Has not occurred.
